//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int customerID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> accountStatus { get; set; }
        public string registerDate { get; set; }
    }
}
