//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExtraService
    {
        public int extraID { get; set; }
        public int productID { get; set; }
        public Nullable<int> serpmeKahvalti { get; set; }
        public Nullable<int> yemekAlkolsuz { get; set; }
        public Nullable<int> kahvalti { get; set; }
        public Nullable<int> yemekAlkollu { get; set; }
        public Nullable<int> kokteylAlkolsuz { get; set; }
        public Nullable<int> kokteylAlkollu { get; set; }
        public Nullable<int> volkan { get; set; }
        public Nullable<int> kemanci { get; set; }
        public Nullable<int> dansoz { get; set; }
        public Nullable<int> lazerGosterisi { get; set; }
        public Nullable<int> fasilGrubu { get; set; }
        public Nullable<int> dj { get; set; }
        public Nullable<int> garson { get; set; }
        public Nullable<int> susleme { get; set; }
    }
}
