//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int imageID { get; set; }
        public int productId { get; set; }
        public string img1 { get; set; }
        public string img1s { get; set; }
        public string img2 { get; set; }
        public string img2s { get; set; }
        public string img3 { get; set; }
        public string img3s { get; set; }
        public string img4 { get; set; }
        public string img4s { get; set; }
        public string img5 { get; set; }
        public string img5s { get; set; }
        public string img6 { get; set; }
        public string img6s { get; set; }
        public string img7 { get; set; }
        public string img7s { get; set; }
        public string img8 { get; set; }
        public string img8s { get; set; }
        public string img9 { get; set; }
        public string img9s { get; set; }
        public string img10 { get; set; }
        public string img10s { get; set; }
    }
}
