//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusicSystem
    {
        public int musicID { get; set; }
        public Nullable<bool> bluetooth { get; set; }
        public Nullable<bool> usb { get; set; }
        public Nullable<bool> aux { get; set; }
    }
}
