//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductRank
    {
        public int rankID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> rankPoint { get; set; }
    }
}
