//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int paymentID { get; set; }
        public Nullable<bool> creditCard { get; set; }
        public Nullable<bool> bankCard { get; set; }
    }
}
