//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int productID { get; set; }
        public string name { get; set; }
        public string descriptionTitle { get; set; }
        public string descriptionP1 { get; set; }
        public string descriptionP2 { get; set; }
        public string descriptionP3 { get; set; }
        public Nullable<int> picturesID { get; set; }
        public Nullable<int> discountPercentage { get; set; }
        public Nullable<bool> discountAvailable { get; set; }
        public Nullable<int> suplierID { get; set; }
        public Nullable<int> minRentHour { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<int> yapimYili { get; set; }
        public Nullable<byte> cabinetNumber { get; set; }
        public Nullable<bool> captain { get; set; }
        public Nullable<double> length { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> musicSystemID { get; set; }
        public Nullable<int> oneStarNum { get; set; }
        public Nullable<int> twoStarNum { get; set; }
        public Nullable<int> threeStarNum { get; set; }
        public Nullable<int> fourStarNum { get; set; }
        public Nullable<int> fiveStarNum { get; set; }
        public Nullable<double> starAverage { get; set; }
        public Nullable<int> guestCapacity { get; set; }
        public Nullable<int> guestLanchCapacity { get; set; }
        public Nullable<bool> airCondition { get; set; }
    }
}
