//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductType
    {
        public int typeID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<bool> gulet { get; set; }
        public Nullable<bool> yelkenli { get; set; }
        public Nullable<bool> motorYat { get; set; }
        public Nullable<bool> katamaran { get; set; }
        public Nullable<bool> trawler { get; set; }
        public Nullable<bool> lobster { get; set; }
    }
}
