//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReservation
    {
        public int reservationID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> paymentID { get; set; }
        public string createdDate { get; set; }
        public string startDate { get; set; }
        public string finishDate { get; set; }
        public string startTime { get; set; }
        public string finishTime { get; set; }
        public Nullable<bool> cancelled { get; set; }
        public string paymentDate { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> resDetailID { get; set; }
        public Nullable<int> priceHour { get; set; }
        public Nullable<int> quantityHour { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> totalBoatPrice { get; set; }
        public Nullable<int> paidedPrice { get; set; }
        public string tourType { get; set; }
        public string extrasNames { get; set; }
        public Nullable<int> extrasTotalPrice { get; set; }
        public Nullable<int> total { get; set; }
    }
}
