//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuplier
    {
        public int suplierID { get; set; }
        public string companyName { get; set; }
        public string contactName { get; set; }
        public string contactLastName { get; set; }
        public string adres { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string webSite { get; set; }
        public Nullable<int> paymentMethodID { get; set; }
        public Nullable<int> discountPercentage { get; set; }
        public Nullable<int> discountAvailable { get; set; }
        public Nullable<int> currentReservationID { get; set; }
        public byte[] logo { get; set; }
        public Nullable<int> pictureNum { get; set; }
        public Nullable<int> adminAprove { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> statusActive { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
    }
}
