//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYatRezSaatleri
    {
        public int ID { get; set; }
        public int productId { get; set; }
        public string dayDate { get; set; }
        public Nullable<bool> s0 { get; set; }
        public Nullable<bool> s1 { get; set; }
        public Nullable<bool> s2 { get; set; }
        public Nullable<bool> s3 { get; set; }
        public Nullable<bool> s4 { get; set; }
        public Nullable<bool> s5 { get; set; }
        public Nullable<bool> s6 { get; set; }
        public Nullable<bool> s7 { get; set; }
        public Nullable<bool> s8 { get; set; }
        public Nullable<bool> s9 { get; set; }
        public Nullable<bool> s10 { get; set; }
        public Nullable<bool> s11 { get; set; }
        public Nullable<bool> s12 { get; set; }
        public Nullable<bool> s13 { get; set; }
        public Nullable<bool> s14 { get; set; }
        public Nullable<bool> s15 { get; set; }
        public Nullable<bool> s16 { get; set; }
        public Nullable<bool> s17 { get; set; }
        public Nullable<bool> s18 { get; set; }
        public Nullable<bool> s19 { get; set; }
        public Nullable<bool> s20 { get; set; }
        public Nullable<bool> s21 { get; set; }
        public Nullable<bool> s22 { get; set; }
        public Nullable<bool> s23 { get; set; }
    }
}
