//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yatProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTekneEntities : DbContext
    {
        public dbTekneEntities()
            : base("name=dbTekneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblExtraService> tblExtraServices { get; set; }
        public virtual DbSet<tblKullaniciTipleri> tblKullaniciTipleris { get; set; }
        public virtual DbSet<tblMusicSystem> tblMusicSystems { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblProductRank> tblProductRanks { get; set; }
        public virtual DbSet<tblProductType> tblProductTypes { get; set; }
        public virtual DbSet<tblReservation> tblReservations { get; set; }
        public virtual DbSet<tblSuplier> tblSupliers { get; set; }
        public virtual DbSet<tblYatRezSaatleri> tblYatRezSaatleris { get; set; }
        public virtual DbSet<tblImage> tblImages { get; set; }
    }
}
